// Code generated by protoc-gen-cato. DO NOT EDIT.

package books


import (
    
    domainbooks "cato-example-bms/internal/models/domain/books"
    
)


type Books struct {

    Category string ``

    BookClass string ``

    Author *domainbooks.BookAuthor ``

    CreateAt int64 ``

    UpdateAt int64 ``

    Id int64 ``

    Name string ``

}


func (models *Books) TableName() string {
    // bms book info
    
    return `books`
    
}
