// Code generated by protoc-gen-cato. DO NOT EDIT.

package books

type BookBrief struct {
	Id    int64
	Name  string
	Cover string
}

type BookAuthor struct {
	Name    string
	Birth   int64
	Country string
}

type BookDetail struct {
	Brief    *BookBrief
	Category string
	Class    string
	Author   *BookAuthor
}
