// Code generated by protoc-gen-cato. DO NOT EDIT.

package books

import (
	model "cato-example-bms/internal/models/database/books"
	"context"
)

var (
	repo Repo
)

func GetRepo() Repo {
	return repo
}

type Repo interface {
	basic
	extension
}

type basic interface {
	FindByCategoryAndBookClass(ctx context.Context, container *model.Books) ([]*model.Books, error)
	FindById(ctx context.Context, container *model.Books) (*model.Books, error)
	UpdateById(ctx context.Context, data map[string]interface{}, container *model.Books) error
	DeleteById(ctx context.Context, container *model.Books) error
	FindByName(ctx context.Context, container *model.Books) (*model.Books, error)
	UpdateByName(ctx context.Context, data map[string]interface{}, container *model.Books) error
	DeleteByName(ctx context.Context, container *model.Books) error
	Insert(ctx context.Context, data map[string]interface{}) error
}
