// Code generated by protoc-gen-cato. DO NOT EDIT.
package books

import (
	"net/http"
)

type BookManageHttpHandler struct {
	service BookManageService
	tier    BookManageServiceTier
}

func (s *BookManageHttpHandler) Init(service BookManageService, tier BookManageServiceTier) {
	s.service = service
	s.tier = tier
}

func (s *BookManageHttpHandler) GetRoutersMap() map[string]http.HandlerFunc {
	funcs := make(map[string]http.HandlerFunc)
	funcs["GET /v1/search/category"] = func(w http.ResponseWriter, r *http.Request) {
		ctx, request := s.tier.BuildSearchBooksByCategoryV1Request(r)
		response, err := s.service.SearchBooksByCategoryV1(ctx, request)
		s.tier.WrapSearchBooksByCategoryV1Response(w, response, err)
	}
	return funcs
}

func (s *BookManageHttpHandler) GetRouterGroupBase() string {
	return "/bms/api"
}
