// Code generated by protoc-gen-cato. DO NOT EDIT.
package books

import (
	"net/http"
)

type BookManageServiceHttpHandler struct {
	service   BookManageServiceService
	tier      BookManageServiceServiceTier
	container BookManageServiceServiceContainer
}

func NewBookManageServiceHttpHandler(
	service BookManageServiceService,
	tier BookManageServiceServiceTier,
	container BookManageServiceServiceContainer,
) *BookManageServiceHttpHandler {
	s := new(BookManageServiceHttpHandler)
	s.service = service
	s.tier = tier
	s.container = container
	return s
}

func (handler *BookManageServiceHttpHandler) GetRoutersMap() map[string]http.HandlerFunc {
	handler.container.Set("GET", "/v1/search", func(w http.ResponseWriter, r *http.Request) {
		ctx, request := handler.tier.BuildSearchBooksByCategoryV1Request(r)
		response, err := handler.service.SearchBooksByCategoryV1(ctx, request)
		handler.tier.WrapSearchBooksByCategoryV1Response(w, response, err)
	})
	return handler.container.ToMap()
}

func (handler *BookManageServiceHttpHandler) GetRouterGroupBase() string {
	return ""
}
