// Code generated by protoc-gen-cato. DO NOT EDIT.
package books

import (
	inspectbooks "cato-example-bms/internal/inspect/books"
	"context"
	"net/http"
)

type BookManageServiceService interface {
	SearchBooksByCategoryV1(ctx context.Context, request *inspectbooks.SearchBooksByCategoryRequest) (*inspectbooks.SearchBooksByCategoryResponse, error)
}

type BookManageServiceServiceTier interface {
	BuildSearchBooksByCategoryV1Request(input *http.Request) (context.Context, *inspectbooks.SearchBooksByCategoryRequest)
	WrapSearchBooksByCategoryV1Response(output http.ResponseWriter, resp *inspectbooks.SearchBooksByCategoryResponse, err error)
}

type BookManageServiceServiceContainer interface {
	Set(method string, path string, runner func(w http.ResponseWriter, r *http.Request))
	Get(method string, path string) (func(w http.ResponseWriter, r *http.Request), bool)
	ToMap() map[string]http.HandlerFunc
}
