// Code generated by protoc-gen-cato. DO NOT EDIT.
package books

import (
	"context"
	"net/http"

	booksinspect "cato-example-bms/internal/inspect/books"
)

type BookManageService interface {
	SearchBooksByCategoryV1(ctx context.Context, request *booksinspect.SearchBooksByCategoryRequest) (*booksinspect.SearchBooksByCategoryResponse, error)
}

type BookManageServiceTier interface {
	BuildSearchBooksByCategoryV1Request(input *http.Request) (context.Context, *booksinspect.SearchBooksByCategoryRequest)
	WrapSearchBooksByCategoryV1Response(output http.ResponseWriter, resp *booksinspect.SearchBooksByCategoryResponse, err error)
}
