// Code generated by protoc-gen-cato. DO NOT EDIT.

package books

import (
	inspectbooks "cato-example-bms/internal/inspect/books"
	"context"
	"net/http"
)

type BookManageServiceService interface {
	SearchBooksByCategoryV1(ctx context.Context, request *inspectbooks.SearchBooksByCategoryRequest) (*inspectbooks.SearchBooksByCategoryResponse, error)
}

type BookManageServiceServiceTier interface {
	BeforeSearchBooksByCategoryV1Request(input *http.Request) (context.Context, *inspectbooks.SearchBooksByCategoryRequest)
	AfterSearchBooksByCategoryV1Response(output http.ResponseWriter, resp *inspectbooks.SearchBooksByCategoryResponse, err error)
}
