// Code generated by protoc-gen-cato. DO NOT EDIT.

package common

type RequestTraceHelper struct {
	XRequestId string
}

type ResponseCommonStruct struct {
	BizCode    string
	BizMessage string
}

type CommonHeaderStruct struct {
	XTraceId  string
	XSignInfo string
}

type TableBaseModel struct {
	Id         int64
	CreateTime int64
	UpdateTime int64
}
