// Code generated by protoc-gen-cato. DO NOT EDIT.

package books

import (

	inspectcommon "cato-example-bms/internal/inspect/common"
	domainbooks "cato-example-bms/internal/models/domain/books"
)

type SearchBooksByCategoryRequest struct {
	Category string
}

func (r SearchBooksByCategoryRequest) UnmrashalFrom(request []byte) error {
	return nil
}

type SearchBooksByCategoryResponse struct {
	Base    *inspectcommon.ResponseCommonStruct
	Results []*domainbooks.BookBrief
}

